### PR TITLE
Fixed path prefixing

### PR DESCRIPTION
**Pull request by vogt31337**
Hi! Thanks for building this dash keycloak integration :)

I had a similar issue compared to #12 I fixed it with this PR, by attaching the prefix_callback_path directly to self.callback. 
This fixed this 302 loop for me.

BR

### CODE REVIEW

**Comment by friederikemeier** [comment]
Nice fix!

**Comment by emilhe** [comment]
@gedemagt Do you think this PR can be merged?

**Comment by gedemagt** [comment]
Look good. Could you remove the comments? Then I think we can merge .

**Comment by vogt31337** [comment]
@gedemagt I think I have to create another PR for that. But I've allowed "edits by maintainers", so you guys should be able to modify it. The comments are basically your old code...

**Comment by vogt31337** [comment]
I've added / removed comments.

**Pull request merged**
